# Generated by Django 4.2.29 on 2026-03-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='purchased_products',
            field=models.ManyToManyField(blank=True, related_name='buyers', to='products.product'),
        ),
    ]
