# Generated by Django 4.2.29 on 2026-03-25 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="is_preview",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="book_file",
            field=models.FileField(blank=True, null=True, upload_to="books/"),
        ),
        migrations.AddField(
            model_name="tableofcontentsentry",
            name="is_preview",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="CourseProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("progress_percentage", models.PositiveSmallIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_chapters",
                    models.ManyToManyField(
                        blank=True,
                        related_name="progress_records",
                        to="products.chapter",
                    ),
                ),
                (
                    "current_chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="products.chapter",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        limit_choices_to={"type": "course"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_progress_records",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Progreso de curso",
                "verbose_name_plural": "Progresos de cursos",
                "unique_together": {("user", "product")},
            },
        ),
        migrations.CreateModel(
            name="CourseCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf_file", models.FileField(upload_to="certificates/")),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        limit_choices_to={"type": "course"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado de curso",
                "verbose_name_plural": "Certificados de cursos",
                "unique_together": {("user", "product")},
            },
        ),
        migrations.CreateModel(
            name="BookDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("max_downloads", models.PositiveIntegerField(default=3)),
                ("last_downloaded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_downloads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Descarga de libro",
                "verbose_name_plural": "Descargas de libros",
                "unique_together": {("user", "product")},
            },
        ),
    ]
