# Generated by Django 4.2.30 on 2026-05-09 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_type_6c9b75_idx',
            old_name='products_pro_type_9d3dd6_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_categor_50f5f1_idx',
            old_name='products_pro_categor_0749f6_idx',
        ),
    ]
