# Generated by Django 4.2.30 on 2026-05-17

from django.db import migrations, models


def backfill_localized_product_fields(apps, schema_editor):
    Product = apps.get_model("products", "Product")

    title_map = {
        "Python desde Cero hasta Avanzado": {
            "es": "Python desde Cero hasta Avanzado",
            "en": "Python from Zero to Advanced",
        },
        "Desarrollo Web Full Stack con React y Node.js": {
            "es": "Desarrollo Web Full Stack con React y Node.js",
            "en": "Full Stack Web Development with React and Node.js",
        },
        "Machine Learning con Python": {
            "es": "Machine Learning con Python",
            "en": "Machine Learning with Python",
        },
        "DevOps: Docker, Kubernetes y CI/CD": {
            "es": "DevOps: Docker, Kubernetes y CI/CD",
            "en": "DevOps: Docker, Kubernetes and CI/CD",
        },
        "Desarrollo Mobile con React Native": {
            "es": "Desarrollo Mobile con React Native",
            "en": "Mobile Development with React Native",
        },
        "PostgreSQL: Bases de Datos Avanzadas": {
            "es": "PostgreSQL: Bases de Datos Avanzadas",
            "en": "PostgreSQL: Advanced Databases",
        },
        "Clean Code: Manual de Estilo para el Desarrollo Ágil": {
            "es": "Clean Code: Manual de Estilo para el Desarrollo Ágil",
            "en": "Clean Code: Style Guide for Agile Development",
        },
        "Python para Data Science": {
            "es": "Python para Data Science",
            "en": "Python for Data Science",
        },
        "Diseño de APIs RESTful": {
            "es": "Diseño de APIs RESTful",
            "en": "Designing RESTful APIs",
        },
        "Deep Learning con TensorFlow": {
            "es": "Deep Learning con TensorFlow",
            "en": "Deep Learning with TensorFlow",
        },
    }

    description_map = {
        "Aprende Python desde los fundamentos hasta conceptos avanzados. Incluye proyectos prácticos y ejercicios.": {
            "es": "Aprende Python desde los fundamentos hasta conceptos avanzados. Incluye proyectos prácticos y ejercicios.",
            "en": "Learn Python from the fundamentals to advanced concepts. Includes practical projects and exercises.",
        },
        "Conviértete en desarrollador Full Stack. Aprende React, Node.js, Express y MongoDB.": {
            "es": "Conviértete en desarrollador Full Stack. Aprende React, Node.js, Express y MongoDB.",
            "en": "Become a Full Stack developer. Learn React, Node.js, Express, and MongoDB.",
        },
        "Domina los fundamentos del Machine Learning con Python, scikit-learn y TensorFlow.": {
            "es": "Domina los fundamentos del Machine Learning con Python, scikit-learn y TensorFlow.",
            "en": "Master Machine Learning fundamentals with Python, scikit-learn, and TensorFlow.",
        },
        "Aprende DevOps moderno: Docker, Kubernetes, Jenkins y automatización completa.": {
            "es": "Aprende DevOps moderno: Docker, Kubernetes, Jenkins y automatización completa.",
            "en": "Learn modern DevOps: Docker, Kubernetes, Jenkins, and full automation.",
        },
        "Crea aplicaciones móviles nativas para iOS y Android con React Native.": {
            "es": "Crea aplicaciones móviles nativas para iOS y Android con React Native.",
            "en": "Build native mobile apps for iOS and Android with React Native.",
        },
        "Domina PostgreSQL: desde consultas básicas hasta optimización avanzada.": {
            "es": "Domina PostgreSQL: desde consultas básicas hasta optimización avanzada.",
            "en": "Master PostgreSQL: from basic queries to advanced optimization.",
        },
        "El libro esencial sobre código limpio y mejores prácticas de programación.": {
            "es": "El libro esencial sobre código limpio y mejores prácticas de programación.",
            "en": "The essential book on clean code and programming best practices.",
        },
        "Guía completa de Python para análisis de datos con pandas, NumPy y matplotlib.": {
            "es": "Guía completa de Python para análisis de datos con pandas, NumPy y matplotlib.",
            "en": "Complete Python guide for data analysis with pandas, NumPy, and matplotlib.",
        },
        "Todo lo que necesitas saber sobre diseño de APIs REST modernas y escalables.": {
            "es": "Todo lo que necesitas saber sobre diseño de APIs REST modernas y escalables.",
            "en": "Everything you need to know about designing modern, scalable REST APIs.",
        },
        "Aprende Deep Learning desde cero con TensorFlow y Keras.": {
            "es": "Aprende Deep Learning desde cero con TensorFlow y Keras.",
            "en": "Learn Deep Learning from scratch with TensorFlow and Keras.",
        },
    }

    for product in Product.objects.all():
        known_title = title_map.get(product.title)
        known_description = description_map.get(product.description)

        if known_title:
            product.title_es = known_title["es"]
            product.title_en = known_title["en"]
        elif product.language == "english":
            if not product.title_en:
                product.title_en = product.title
            if not product.title_es:
                product.title_es = product.title
        else:
            if not product.title_es:
                product.title_es = product.title
            if not product.title_en:
                product.title_en = product.title

        if known_description:
            product.description_es = known_description["es"]
            product.description_en = known_description["en"]
        elif product.language == "english":
            if not product.description_en:
                product.description_en = product.description
            if not product.description_es:
                product.description_es = product.description
        else:
            if not product.description_es:
                product.description_es = product.description
            if not product.description_en:
                product.description_en = product.description

        product.save(
            update_fields=[
                "title_es",
                "title_en",
                "description_es",
                "description_en",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0004_rename_products_pro_type_9d3dd6_idx_products_pr_type_6c9b75_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="title_es",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="title_en",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="description_es",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunPython(
            backfill_localized_product_fields, migrations.RunPython.noop
        ),
    ]
